<a href="https://colab.research.google.com/github/ASO2001052/AI_teach2020/blob/master/20201009AI0205_selectAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip uninstall scikit-learn
!pip install scikit-learn==0.20 --ignore-installed

Uninstalling scikit-learn-0.22.2.post1:
  Would remove:
    /usr/local/lib/python3.6/dist-packages/scikit_learn-0.22.2.post1.dist-info/*
    /usr/local/lib/python3.6/dist-packages/sklearn/*
Proceed (y/n)? y
  Successfully uninstalled scikit-learn-0.22.2.post1
     |████████████████████████████████| 5.3MB 2.6MB/s 
     |████████████████████████████████| 14.9MB 279kB/s 
     |████████████████████████████████| 25.9MB 1.3MB/s 
ERROR: tensorflow 2.3.0 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.3 which is incompatible.
ERROR: tensorflow 2.3.0 has requirement scipy==1.4.1, but you'll have scipy 1.5.3 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.


In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.utils.testing import all_estimators
import warnings

In [3]:
import urllib.request as req
url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/iris.csv"
savefile = "iris.csv"
req.urlretrieve(url, savefile)
iris_data = pd.read_csv(savefile, encoding="utf-8")
iris_data.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [4]:
y = iris_data.loc[:, "Name"]
x = iris_data.loc[:, ["SepalLength", "SepalWidth", "PetalLength", "PetalWidth"]]

print(y.head())
print(x.head())

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Name, dtype: object
   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2


In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2, train_size=0.8, shuffle=True)
print(x_train.head())
print(y_train.head())
print(x_test.head())
print(y_test.head())

     SepalLength  SepalWidth  PetalLength  PetalWidth
149          5.9         3.0          5.1         1.8
53           5.5         2.3          4.0         1.3
137          6.4         3.1          5.5         1.8
105          7.6         3.0          6.6         2.1
101          5.8         2.7          5.1         1.9
149     Iris-virginica
53     Iris-versicolor
137     Iris-virginica
105     Iris-virginica
101     Iris-virginica
Name: Name, dtype: object
    SepalLength  SepalWidth  PetalLength  PetalWidth
74          6.4         2.9          4.3         1.3
30          4.8         3.1          1.6         0.2
37          4.9         3.1          1.5         0.1
85          6.0         3.4          4.5         1.6
38          4.4         3.0          1.3         0.2
74    Iris-versicolor
30        Iris-setosa
37        Iris-setosa
85    Iris-versicolor
38        Iris-setosa
Name: Name, dtype: object


In [6]:
allAlgorithms = all_estimators(type_filter="classifier")
warnings.filterwarnings('ignore')

In [7]:
for (name, algorithm) in allAlgorithms:
  try:
    clf = algorithm()
    clf.fit(x_train, y_train)
    y_pred =clf.predict(x_test)
    print(name, "の正解率 = ", accuracy_score(y_test, y_pred))

  except Exception as e:
    print("\033[31m" + "Error: \033[0m", name, ":", e.args)
  # else:
    # print("正常系です")

AdaBoostClassifier の正解率 =  0.9333333333333333
BaggingClassifier の正解率 =  0.9
BernoulliNB の正解率 =  0.13333333333333333
CalibratedClassifierCV の正解率 =  0.8666666666666667
ComplementNB の正解率 =  0.5666666666666667
DecisionTreeClassifier の正解率 =  0.9
ExtraTreeClassifier の正解率 =  0.9
ExtraTreesClassifier の正解率 =  0.9333333333333333
GaussianNB の正解率 =  0.9333333333333333
GaussianProcessClassifier の正解率 =  0.9333333333333333
GradientBoostingClassifier の正解率 =  0.9
KNeighborsClassifier の正解率 =  0.9333333333333333
LabelPropagation の正解率 =  0.9333333333333333
LabelSpreading の正解率 =  0.9333333333333333
LinearDiscriminantAnalysis の正解率 =  0.9666666666666667
LinearSVC の正解率 =  0.9333333333333333
LogisticRegression の正解率 =  0.9
LogisticRegressionCV の正解率 =  0.8666666666666667
MLPClassifier の正解率 =  0.9333333333333333
MultinomialNB の正解率 =  0.5666666666666667
NearestCentroid の正解率 =  0.8666666666666667
NuSVC の正解率 =  0.9333333333333333
PassiveAggressiveClassifier の正解率 =  0.5666666666666667
Perceptron の正解率 =  0.9
Quadratic

In [8]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [9]:
kfold_cv = KFold( n_splits=5, shuffle=True)
for( name, algorithm ) in allAlgorithms:
  try:
    clf = algorithm()
    if hasattr(clf, "score"):
      scores = cross_val_score(clf, x, y, cv=kfold_cv)
      print(name, "の正解率 = ")
      print(scores)
  except:
    pass

AdaBoostClassifier の正解率 = 
[0.9        0.96666667 0.96666667 0.9        0.9       ]
BaggingClassifier の正解率 = 
[0.9        0.96666667 0.96666667 0.86666667 0.96666667]
BernoulliNB の正解率 = 
[0.16666667 0.23333333 0.23333333 0.2        0.2       ]
CalibratedClassifierCV の正解率 = 
[0.93333333 0.93333333 0.86666667 0.9        0.96666667]
ComplementNB の正解率 = 
[0.63333333 0.6        0.7        0.6        0.8       ]
DecisionTreeClassifier の正解率 = 
[0.93333333 0.93333333 0.93333333 0.96666667 1.        ]
ExtraTreeClassifier の正解率 = 
[0.96666667 1.         0.96666667 0.93333333 0.96666667]
ExtraTreesClassifier の正解率 = 
[1.         1.         0.86666667 0.9        0.96666667]
GaussianNB の正解率 = 
[0.93333333 0.96666667 0.93333333 0.96666667 0.96666667]
GaussianProcessClassifier の正解率 = 
[1.         0.96666667 1.         0.9        0.96666667]
GradientBoostingClassifier の正解率 = 
[0.96666667 1.         0.9        0.96666667 1.        ]
KNeighborsClassifier の正解率 = 
[0.96666667 0.93333333 0.96666667 0.9666666

In [10]:
from sklearn.model_selection import cross_validate

In [11]:
kfold_cv = KFold( n_splits=5, shuffle=True)
for( name, algorithm ) in allAlgorithms:
  try:
    clf = algorithm()
    if hasattr(clf, "score"):
      scores = cross_validate(clf, x, y, cv=kfold_cv)
      print(name, "の正解率 = ")
      print(scores)
  except:
    pass

AdaBoostClassifier の正解率 = 
{'fit_time': array([0.06855249, 0.06081486, 0.05933976, 0.06165981, 0.06207323]), 'score_time': array([0.00595784, 0.00563264, 0.00584054, 0.00670362, 0.00587058]), 'test_score': array([0.96666667, 1.        , 0.9       , 1.        , 0.9       ]), 'train_score': array([0.95833333, 0.95      , 0.975     , 0.95      , 0.95833333])}
BaggingClassifier の正解率 = 
{'fit_time': array([0.01519227, 0.0128026 , 0.01298451, 0.01269913, 0.01274943]), 'score_time': array([0.00176477, 0.00163484, 0.0017302 , 0.0016048 , 0.00162959]), 'test_score': array([1.        , 0.93333333, 0.96666667, 0.96666667, 0.93333333]), 'train_score': array([0.99166667, 0.99166667, 0.99166667, 1.        , 1.        ])}
BernoulliNB の正解率 = 
{'fit_time': array([0.00286031, 0.00162792, 0.00164056, 0.00160241, 0.00156879]), 'score_time': array([0.00106716, 0.0007925 , 0.00076461, 0.00077486, 0.00081801]), 'test_score': array([0.26666667, 0.3       , 0.23333333, 0.23333333, 0.23333333]), 'train_score': 

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

In [13]:
parameters = [
              {"C":[1, 10, 100, 1000], "kernel":["linear"]},
              {"C":[1, 10, 100, 1000], "kernel":["rbf"], "gamma":[0.001, 0.0001]},
              {"C":[1, 10, 100, 1000], "kernel":["sigmoid"], "gamma":[0.001, 0.0001]}
]

clf_svc = SVC()
clf_svc.fit(x_train, y_train)
y_pred_svc = clf_svc.predict(x_test)
print("普通の学習の正解率 = ", accuracy_score(y_test, y_pred))

kfold_cv = KFold(n_splits=5, shuffle=True)
clf_grid = GridSearchCV(SVC(), parameters, cv=kfold_cv)
clf_grid.fit(x_train, y_train)
print("最適なパラメーター = ", clf_grid.best_estimator_)

y_pred_grid = clf_grid.predict(x_test)
print("グリッドサーチの正解率 = ", accuracy_score(y_test, y_pred))


普通の学習の正解率 =  0.9333333333333333
最適なパラメーター =  SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
グリッドサーチの正解率 =  0.9333333333333333


In [14]:
import numpy as np

In [18]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [16]:
print(np.zeros(10))
print(np.zeros((3,2)))
print(np.ones(2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1.]


In [19]:
print(np.arange(5))
print(np.arange(2,9))
print(np.arange(5,8,0.5))

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


In [21]:
a = np.array([1,2,3,4,5])
b = a*2
print(b)
x = np.arange(10)
print(x)
y = 3*x+5
print(y)

[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17 20 23 26 29 32]


In [23]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [24]:
a = np.array([[1,2,3],[4,5,6]])
print("a=",a)
b = a.flatten()
print("b=",b)

a = np.array([[1,2,3],[4,5,6]])
print(a)
b = a.reshape(3,2)
print(b)

a= [[1 2 3]
 [4 5 6]]
b= [1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [26]:
v = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = v[0]
print(a)
b = v[1:]
print(b)
c = v[:,0]
print(c)

[1 2 3]
[[4 5 6]
 [7 8 9]]
[1 4 7]
